name: finetune
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.12.12
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy-base=1.24.3
  - openssl=3.0.12
  - python=3.8.18
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboardx=2.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.26.1
      - aiofiles==23.2.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autopep8==2.0.4
      - backcall==0.2.0
      - bitsandbytes==0.42.0
      - black==23.12.1
      - brotli==1.1.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmudict==1.0.16
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==2.16.1
      - decorator==5.1.1
      - dill==0.3.7
      - docstring-parser==0.15
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.109.0
      - ffmpy==0.3.1
      - filelock==3.13.1
      - fire==0.5.0
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - gradio==4.14.0
      - gradio-client==0.8.0
      - grpcio==1.60.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.2
      - humanfriendly==10.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - inflate64==1.0.0
      - ipython==8.12.3
      - jedi==0.19.1
      - jellyfish==1.0.3
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonpickle==3.0.2
      - jsonschema==4.21.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - llama-recipes==0.0.1
      - loralib==0.1.2
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - multivolumefile==0.2.3
      - music21==8.3.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.2.2
      - optimum==1.16.1
      - orjson==3.9.10
      - packaging==23.2
      - pandas==2.0.3
      - parso==0.8.3
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pip==23.3.2
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.1.0
      - prompt-toolkit==3.0.43
      - pronouncing==0.2.0
      - protobuf==4.25.2
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py7zr==0.20.8
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybcj==1.0.2
      - pycodestyle==2.11.1
      - pycryptodomex==3.20.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pyppmd==1.1.0
      - python-dateutil==2.8.2
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzstd==0.15.9
      - referencing==0.32.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.9
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - segtok==1.5.11
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - setuptools==69.0.3
      - shellingham==1.5.4
      - shtab==1.6.5
      - sniffio==1.3.0
      - stack-data==0.6.3
      - starlette==0.35.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - textblob==0.17.1
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tokenize-rt==5.2.0
      - tokenizers==0.15.0
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.0
      - tqdm==4.66.1
      - traitlets==5.14.1
      - transformers==4.36.2
      - triton==2.2.0
      - trl==0.7.9
      - typer==0.9.0
      - typing-extensions==4.9.0
      - tyro==0.6.5
      - tzdata==2023.4
      - urllib3==2.1.0
      - uvicorn==0.26.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - websockets==11.0.3
      - werkzeug==3.0.1
      - xxhash==3.4.1
      - yake==0.4.8
      - yarl==1.9.4
      - zipp==3.17.0
      - peft==0.7.2.dev0
      - torch==2.2.0+cu118